name: build_run_tests

on: [ push ]

env:
  SHORT_SHA: $(git rev-parse --short=8 ${{ github.sha }})

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: update apt-get sources
        run: sudo apt-get update
      - name: install gcc-9
        run: sudo apt-get install -y gcc-9 g++-9 build-essential
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_C_COMPILER=gcc-9 ..
      - name: build
        run: cmake --build build --target testing-all
      - name: test
        run: cd build && ctest
      - name: Send message to Slack if job has failed
        if: ${{ failure() }}
        run: |
          curl -F $'text=⚠️ *Compilation failed for gcc on Ubuntu!*\nPlease check status on the <https://github.com/MarbleHE/ABC/actions/runs/${{ github.run_id }}|Actions dashboard>.\Consider the changes made in the most recent git commit <https://github.com/MarbleHE/ABC/commit/${{ github.sha }}|`${{ env.SHORT_SHA }}`>.' -F channel=batching-compiler -H "Authorization: Bearer ${{ secrets.SLACK_APP_TOKEN }}" https://slack.com/api/chat.postMessage
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
      - name: build
        run: cmake --build build --target testing-all
      - name: test
        run: cd build && ctest
      - name: Send message to Slack if job has failed
        if: ${{ failure() }}
        run: |
          curl -F $'text=⚠️ *Compilation failed for clang on macOS!*\nPlease check status on the <https://github.com/MarbleHE/ABC/actions/runs/${{ github.run_id }}|Actions dashboard>.\Consider the changes made in the most recent git commit <https://github.com/MarbleHE/ABC/commit/${{ github.sha }}|`${{ env.SHORT_SHA }}`>.' -F channel=batching-compiler -H "Authorization: Bearer ${{ secrets.SLACK_APP_TOKEN }}" https://slack.com/api/chat.postMessage
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          md build
          cd build
          cmake -DCMAKE_CXX_FLAGS="/W4 /WX" -G "NMake Makefiles" ..
      - name: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build build --target testing-all
      - name: test
        shell: cmd
        run: cd build && ctest
      - name: Send message to Slack if job has failed
        if: ${{ failure() }}
        run: |
          curl -F $'text=⚠️ *Compilation failed for MSVSC on Windows!*\nPlease check status on the <https://github.com/MarbleHE/ABC/actions/runs/${{ github.run_id }}|Actions dashboard>.\Consider the changes made in the most recent git commit <https://github.com/MarbleHE/ABC/commit/${{ github.sha }}|`${{ env.SHORT_SHA }}`>.' -F channel=batching-compiler -H "Authorization: Bearer ${{ secrets.SLACK_APP_TOKEN }}" https://slack.com/api/chat.postMessage
